### ISSUE TITLE
Letters don't immediately reflect Shift/CapsLock changes

### ISSUE THREAD

**Issue by geofrey** [8VIM/8VIM#12]
When tapping the top quadrant to switch in or out of shift modes, the on-screen letter previews don't switch to their shifted or unshifted versions.

Re-displaying the circle keyboard is enough of a refresh to get the correct characters - For example, hiding the on-screen keyboard and subsequently re-selecting a text field, or entering the edit controls screen and then returning to the circle.

**Comment by flide** [comment]
Yes, this is something I have not been able to fix for some time now. Whenever the shift modes are changed, I invalidate the view in hopes that it will be redrawn, but they don't... since this never actually bothered me very much I have not done any research as to why the redrawing does not happen instantly.

**Comment by flide** [comment]
Fixed
