### ISSUE TITLE
[Iteration Request:] Add "Add German Layout" to the Iteration 7 Milestones

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#142]
Soon, I'll be done with https://github.com/flide/8VIM/discussions/138.

**Comment by flide** [comment]
If it's done, I will add it to the release, if it's not it will be next. But since you guys are making great progress, I am really hoping we should. 

Also, before new languages can be incorporated, I need to refactor the code to make dynamic changes to the xpad to accept language change. I am working on it, not sure it is going to be super easy though.

**Comment by Glitchy-Tozier** [comment]
Somehow I checked Github only 3 minutes after you replied  xD
>If it's done, I will add it to the release, if it's not it will be next. But since you guys are making great progress, I am really hoping we should.

Makes sense.

> Also, before new languages can be incorporated, I need to refactor the code to make dynamic changes to the xpad to accept language change. I am working on it, not sure it is going to be super easy though.

Right, I was gonna ask: do you want a new issue for that?

**Comment by flide** [comment]
Yea that will be great.
