### ISSUE TITLE
open selection keypad by default

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#150]
In the input field has something selected before hand, then by default open selection keypad.

**Comment by Glitchy-Tozier** [comment]
I have never encountered a screnario where I could highlight something and then open the keyboard!

How did you do it?

**Comment by flide** [comment]
by clicking on the address bar on an active page in firefor.

**Comment by Glitchy-Tozier** [comment]
Ah yeah, forgot about that!
In that case, I think it's better to keep the normal keyboard however!

Especially since Firefox (and other browsers as well) have the feature that you can long-click the address-bar and immediately copy or paste & go.

If I actually short-click on the address bar, I want to edit the URL. And in that case, the normal keypad is more helpful.

**Comment by flide** [comment]
Huh!! I never knew about this feature of firefox. Makes sense actually, don't know why I never tried...

Anyways, apart from this I know of no use case. If no one reports in support for this feature, say within 20 days, I will cancel this.
