### ISSUE TITLE
Ideas to insert accented characters

### ISSUE THREAD

**Issue by bagnacauda** [8VIM/8VIM#159]
Hi, I started to use the keyboard and I love it but I can't use for daily typing just because in Italian we have accented letters. 
While this is not nearly as bad as in German, it would be nice to insert accented letters.

One way I thought it could be done is by using a compose key. You select the compose key, via an actual key or a gesture and then procede to write as usual, interpreting the sequence as a special character. In this case you would need a way to make the application know you finished the sequence, for example by releasing the finger or by selecting once again the compose key.

Another solution I thought it could be feasible is to have a dedicated keyboard for accented letters that activates when you press a special key or make a gesture, lets you insert your accented letter and then goes back to the "normal mode".

I think that both could be feasible as the layout doesn't have to change that much, but probably it should be an optional feature since English doesn't really need it, even though it could be handy to type for example fractions or other symbols.

**Comment by Glitchy-Tozier** [comment]
Hey @bagnacauda, Thank you for your ideas!  :)

You might be interested in this: There already is a discussion regarding this topic here: https://github.com/flide/8VIM/discussions/65

I suggest closing this issue and posting your ideas there.
If possible, i also suggest first reading the previous posts on this topic (in https://github.com/flide/8VIM/discussions/65), as some of your ideas may already have been discussed.

Warning: it's a _LONG_ discussion with _LONG_ posts.
(For which I partially am to blame.)

**Comment by adaschma** [comment]
Hi @bagnacauda 
we now have a version of 8vim with the Italian accented characters: https://github.com/adamschmalhofer/8VIM/releases/tag/italian-1

The way it works is that we have new gestures based on the gesture of the standard Latin character. When you want to type the "è" you start with the gesture for "e": "center -> bottom -> left" but before you return to the center you reverse the circular motion "-> bottom" and only then return to the center "-> center". OTOH if you want to type the "é" you start just the same with the "e": "center -> bottom -> left", but before you return to the center instead of reversing the circular motion by one sector you go back two sectors: "-> bottom -> right" and then again return to the center "-> center". It might become clearer after playing around with the keyboard. 

Would love to hear if it works well for you.

**Comment by mutageneral** [comment]
> The way it works is that we have new gestures based on the gesture of the standard Latin character. When you want to type the "è" you start with the gesture for "e": "center -> bottom -> left" but before you return to the center you reverse the circular motion "-> bottom" and only then return to the center "-> center". OTOH if you want to type the "é" you start just the same with the "e": "center -> bottom -> left", but before you return to the center instead of reversing the circular motion by one sector you go back two sectors: "-> bottom -> right" and then again return to the center "-> center". It might become clearer after playing around with the keyboard.

This is not in the readme or next to the diacritic layout option. I had to search the issues to find how to use the keyboard properly. Maybe this could be added to the readme?
