### ISSUE TITLE
Support custom letter layout

### ISSUE THREAD

**Issue by CaptainBlagbird** [8VIM/8VIM#20]
Hi, it would be nice if the user could define an own layout.

Different languages have different letters and letter combinations that are frequently used.
E.g. in German we use "sch" quite often. With the current layout that is optimised for English, this combination is a bit awkward/inefficient to write because S and C are opposite on the same line.

Also different languages might have additional letters that currently are not available.
E.g. in German we use the umlauts (äöü) quite often. Swedish also uses umlauts and the å character. Etc.

Maybe the character set/layout could be defined with configuration files that will be read by the app. That way the community could provide layouts.

**Comment by CaptainBlagbird** [comment]
And if the community would be able to provide custom layouts that way, someone might even use machine learning to create the layout files that can then be read by the app. &rarr; See #14

**Comment by flide** [comment]
I had this in mind when I started to design this keyboard. If you take a look at the file "keyboard_actions.xml" in raw folder under resources, it is completely customizable. I intend to use this structure to allow for user defined gestures as well. Obviously the problem would be display... May be we can define the display characters as well in the same xml file and then in the settings select the configuration the user wants to use.

**Comment by CaptainBlagbird** [comment]
> [keyboard_actions.xml](../blob/master/8vim/src/main/res/raw/keyboard_actions.xml)

Ah I see, nice. Yes an additional XML entry for the display character would work well I think

**Comment by geofrey** [comment]
Give each action element an optional attribute for overriding how it's
displayed on screen. Then everything can all come in the same file.
-gws

**Comment by Glitchy-Tozier** [comment]
This is a very important issue!
The current keyboard is pretty much unusable if you speak German. You would need to constantly switch to another keyboard just to type a full sentence. (because you need ä,ö, and ü).

 I don't know how to best incorporate this, there's just one thing I wanted to bring up: German doesn't trade a, o, and u for ä, ö, and ü. Instead, all of them exist. This raises the question:
If the English x-board already as packed as it is with all slots used up, how will we manage to cram three extra letters in there?

(Oh, just remembered: German also uses "ß", a special "s". I guess it's four additional letters.)

**Comment by flide** [comment]
Can we somehow merge this issue with issue #14 ?
I would like to have all ideas accumulated in a single place.

**Comment by CaptainBlagbird** [comment]
We could close this one and continue on the other one or vice versa. Or an other option would be to close both and create a new issue with both ideas in the top comment.

**Comment by Glitchy-Tozier** [comment]
@CaptainBlagbird Not as fancy as machine learning but you might be interested in this: https://github.com/flide/8VIM/discussions/138
