### ISSUE TITLE
Prompt the user to switch to the 8vim keyboard when using the settings application

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#26]
We already check if the 8vim keyboard has been activated on the system when the user opens up the settings UI.
We should also prompt the user to switch to 8vim when the user is playing with the keyboard settings.

So, just like the activation check, show the user a message that he might want to select 8vim as the current keyboard with two buttons - 
1. Switch - in this case display the inputMethodPicker and let the user switch the keyboard
```

                InputMethodManager imeManager = (InputMethodManager)getApplicationContext().getSystemService(INPUT_METHOD_SERVICE);
                imeManager.showInputMethodPicker();
```
2. Dismiss - Simply dismiss the dialog box.

**Comment by mentalisttraceur** [comment]
Why *mandatory*? Why not just *suggest it*? Mandatory sounds like it would be extremely frustrating under certain circumstances. If I think/remember of a setting change I want for this keyboard while doing something else with another keyboard, then mandatory switch makes it so that instead of

1. navigate to the settings,
2. change the settings,
3. get back to what I was doing

I'd have to

1. navigate to the settings,
2. get prompted to switch keyboard,
3. switch keyboard,
4. change the settings,
5. manually switch keyboard back,
6. get back to what I was doing.

I get that most of the time users just fiddle with the settings until they figure out what they like and then keep it that way. So it is *convenient* and *helpful* for the common case to get a prompt with a reminder that you might want to change keyboard and with a button that takes you to those settings. But *forcing* something because we think it is convenient or helpful is... a really not-nice thing to do to people.

**Comment by flide** [comment]
Actually, that makes a lot of sense. I wasn't thinking of the long term use of the settings-application.

**Comment by flide** [comment]
Done.

**Comment by mentalisttraceur** [comment]
Awesome! Glad to have helped, and happy to see you be so receptive to it!
