### ISSUE TITLE
Dead video URL in the Readme

### ISSUE THREAD

**Issue by nvalis** [8VIM/8VIM#269]
The Youtube link (https://www.youtube.com/watch?v=99vsUF4NuLk) in the [README.md](https://github.com/flide/8VIM#8vim) seems to be dead.
![image](https://user-images.githubusercontent.com/11021253/165181167-67296d7f-2cc1-4a9f-ad6d-cb5adfecfc58.png)

**Comment by falzonv** [comment]
Hello,

I noticed there is another video in the Wiki, and this one still works: https://www.youtube.com/watch?v=q3OuCR0EpGo
The Wiki home page links the same (dead) video than the README, the correct link is in the [Usability Guide](https://github.com/flide/8VIM/wiki/Usability-Guide) page.
The F-Droid description also shows the dead URL.

Just discovered 8Vim yesterday and before seeing this video, I was struggling with the way of typing letters.
The sectors part (backspace, caps, numbers, enter) is pretty straightforward and well explained in the description/wiki.
But the concept for typing letters (that you should start in the circle, go in the quarter showing the letter you want to type, move in the number of quarters relative to the position of the letter on its axis and go back in the circle to input the letter) seems explained nowhere else than in this video even though this is the whole point of a keyboard (typing letters).

Although this video (https://www.youtube.com/watch?v=q3OuCR0EpGo) presents 8pen instead of 8Vim, it is of very good quality and certainly enough to understand the concept of the keyboard. It may not worth the effort to create a new video dedicated to 8Vim since this is one is already very clear, just updating all the links to point towards this video should be good.
(and maybe make a local .mp4 copy of the video in case it would also become unavailable?)

Best regards.

**Comment by ghost** [comment]
I have the same problem.

**Comment by flide** [comment]
updated

**Comment by GlassGruber** [comment]
Also the description on f-droid needs update, thank you!

https://github.com/flide/8VIM/blob/28f1981d1ca50047226adaaff53d7ce62d92a90f/fastlane/metadata/android/en-US/video.txt#L1

https://github.com/flide/8VIM/blob/28f1981d1ca50047226adaaff53d7ce62d92a90f/fastlane/metadata/android/en-US/full_description.txt#L5
