### ISSUE TITLE
Privacy Policy blocks update

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#287]
It seems that I can't release a newer version of the app on playstore as it not requires I provide a privacy policy...
But I don't have one. Can someone help me draft a privacy policy? I collect **literally nothing** from the device.

**Comment by ThomasAH** [comment]
I just asked ChatGPT "Please write a privacy policy for an Android app that does not collect any data." and this was the result, which reads a little bit tongue-in-cheek, but seems appropriate for a privacy policy if the app does not collect data. Feel free to use, modify and share it:

Privacy Policy

Thank you for using our Android app. This Privacy Policy is intended to inform you about the data we do not collect and how we ensure your privacy while using our app.

Data Collection

We do not collect any personal information from you, such as your name, email address, or phone number. We do not collect any sensitive information, such as your location, contacts, or browsing history. Our app does not use cookies, analytics tools, or third-party services that could track your activity.

Data Storage

Since we do not collect any data, we do not store any data on our servers or any third-party servers. Your device may automatically store some data related to your use of the app, such as preferences or settings, but we do not have access to this data.

Data Sharing

We do not share any data with third-party entities, including advertisers, partners, or affiliates. We do not sell any data to anyone.

Data Security

We take reasonable measures to protect any data we may receive or store accidentally, such as through error logs or crash reports. However, since we do not collect any personal or sensitive data, we do not have to take any special security measures.

Changes to Privacy Policy

We may update this Privacy Policy from time to time. If we make any material changes, we will notify you through the app or by email.

Contact Us

If you have any questions or concerns about this Privacy Policy, please contact us at [contact email].

**Comment by flide** [comment]
I created a minimal privacy policy page 
https://github.com/flide/8VIM/wiki/Privacy-Policy

Let me update this on the page instead.

Thanks to you and ChatGPT.
