### ISSUE TITLE
Improve symbol responsiveness on x-pad

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#33]
Currently, the sectors are blank on the X-board and for a new user there is no way of knowing that the bottom sector is for 'enter' or the top sector acts as a shift/caps-lock button or the right sector acts as a backspace button etc. 

The symbols should be at-least displayed for a better UI.

**Comment by Glitchy-Tozier** [comment]
Hey, I'd like to give some feedback, using the picture @flide showed me.

- The Shift-symbol is nice, but I suggest using a more traditional symbol. Honestly, the current symbol look more like a "go up"-arrow, making me think it would have the same functionality as the `center -> up`-motion.
Usually, `SHIFT` is represented by a broader, bigger arrow, which sometimes is empty. Here are a few pictures: https://duckduckgo.com/?q=keyboard+shift&iax=images&ia=images
- I see that in @flide's picture these symbols are cut off (at the bottom) due to him moving the keyboard. I suggest EITHER restricting the movement OR placing the symbols a bit closer to the circle, so that that cutting-off doesn't happen anymore. It looks weird.
- Maybe make that `delete`-symbol just one or two pixels smaller. It looks kind of massive compared to the other three.
(actually, what bothers me might be the fact that the `delete`-symbol is a filled symbol, while the other ones aren't filled. It's a good idea to keep consistency.
Here's a good Video about Icons: https://youtu.be/4hZxo96x48A?t=421
- Overall, great idea adding those symbols, it should really aid usability!  :)

![8vimSectors](https://user-images.githubusercontent.com/59611881/100498428-6ec6a400-3162-11eb-94f0-bc46e20cddcb.jpg)

**Comment by Glitchy-Tozier** [comment]
Also, regarding the Shift-arrow: you could make it responsive.
When it's not activated, it's "empty". When you click Shift, you fill it up, similar to how other mobile keyboards indicate that Shift/Caps-Lock is active.

**Comment by flide** [comment]
points noted
