### ISSUE TITLE
cursor shifts away from textbox 

### ISSUE THREAD

**Issue by Landorlin** [8VIM/8VIM#426]
Using the 8vim cursor (by accident or to ensure a none space ending) sometimes gets me out of the textbox leading to unwanted behavior like eg sending sms. 

**To Reproduce**
1. Open a sms-messenger (i tried the one from simplemobile.com and a preinstalled from samsung) 
2. Write a message and use the cursor. It is now possible to move to the send button sending the message using space. 

**Expected behavior**
The cursor should stay inside it's textbox.

**Smartphone (please complete the following information):**
 - Device: Samsung Xcover 5
 - OS: Android 13

**Additional context**
maybe this is considered not a bug but a feature. In this case there should be an on/off toggle for it.

**Comment by MaethorNaur** [comment]
Hi, could you record the behaviour so I can understand the pattern correctly? I've tried what you described on my Samsung tablet and the built-in SMS messenger but couldn't replicate it.
Also if you swipe from the centre to the right it moves to the send button (as expected). Not sure if that what happened.

**Comment by Aiz0** [comment]
I don't think the regular cursor movement should be able to move focus outside the textbox, especially since the cursor moves so fast.
There are cases where it's useful but most of the times I do it by accident.
Might be better implemented as another type of movement.

If you change the cursor movement behavior to move word by word you can no longer leave the textbox, but you also can't use it to check for extra spaces at the end since the cursor refuses to move there, this is also unexpected behavior.

Tested on version 16.2

**Comment by Landorlin** [comment]
https://github.com/8VIM/8VIM/assets/64330742/cf5c250f-35fd-4871-8735-baafa2ddd49a

i just think the cursor should stay inside its textbox as default like in all other editors    :)

**Comment by Redo11** [comment]
Problem here is because the code uses KEYCODE_DPAD_\* (like in a controller, where it would be expected) instead of MOVE_CURRENT_END_POINT_\* (what most keyboard behavior is like). Should be easy to change. @flide please fix

**Comment by flide** [comment]
I agree

**Comment by MaethorNaur** [comment]
@Redo11 A fix is available from #509. You can download the debug version from the private F-droid repo (https://github.com/8VIM/fdroid)

P.S.: you can install those versions along the stable one they won't

**Comment by Redo11** [comment]
thanks
