### ISSUE TITLE
Keyboard crashes/disappears when pressing emoji key 

### ISSUE THREAD

**Issue by m-rey** [8VIM/8VIM#43]
When I press the emoji button 
![IMG_20201016_080124](https://user-images.githubusercontent.com/42996147/96218899-ffb43800-0f85-11eb-8ba9-2a3fc5a1d7fd.jpg)

The keyboard switches to the next keyboard I have installed. I don't think this is intended. I guess this happens because the keyboard crashes and the system just loads be next one that is installed as fallback.

I'm using the app version `iteration-2`, which is offered here: https://f-droid.org/packages/inc.flide.vim8/
On a Xiaomi Mi Note 10 Pro, running MIUI 12.0.1.0 (Android 10).

**Comment by flide** [comment]
It is partially intended, the keyboard does not crash.

The button is suppose to load a pre-selected keyboard (a feature missing as of iteration 2), and if user has not pre selected any then load the last available keyboard.

I decided to do so because the emojis and gifs and plethora of other stuff was increasing the size of the apk beyond 100mb. 

If you are interested you can try the intended keyboard "https://play.google.com/store/apps/details?id=inc.flide.emojiKeyboard" and with iteration 3 you should be able to set it up so that it opens up without question everytime you want to type emoji's in.

**Comment by m-rey** [comment]
Awesome, thanks for the reply!

Will users have the option to choose the keyboard they want to switch to, when pressing that button?

**Comment by flide** [comment]
yes they will.
