### ISSUE TITLE
Support Landscape mode

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#5]
for 8Vim, in the landscape mode the textfield should be shown on one side of the screen and the keyboard should be shown on another side. This side should be configurable by the user as he/she might prefer left or the right hand.

**Comment by CaptainBlagbird** [comment]
Interesting idea, but is this possible to have a side keyboard in landscape? (It's been a while since I created apps.)

Also I wonder what the benefits of it would be, it would take up about the same amount of space and the remaining space that is used for the messenger/editor/whatever wouldn't be much wider than it is in portrait mode. The only big difference would be that it is more awkward to hold imo.

Maybe for landscape mode the following could be useful:
  - A "normal" qwerty/qwertz keyboard could be displayed
  - The keyboard could be automatically switched to another keyboard like the smiley button does

**Comment by WuerfelDev** [comment]
> for 8Vim, in the landscape mode the textfield should be shown on one side of the screen and the keyboard should be shown on another side. This side should be configurable by the user as he/she might prefer left or the right hand.
Your idea was to create an own preview of the typed text, while the whole keyboard uses the fullscreen size?



With our keyboards landscape is probably one of the biggest problems. IIRC there are some keyboards that can pop out as floating window (?), that might be another idea.


_ |A "normal" qwerty/qwertz keyboard could be displayed  | The keyboard could be automatically switched to another keyboard like the smiley button does
---|---|---
Pro | Dynamic switching | Works fine, good keyboard experience
Con | Need to implement, and will never be as good as other regular, qwerty keyboards | doesn't switch back automatically

Could it be possible to start a background service that listens for orientation changes and switches back automatically?

btw I just added the keyboard switching here: https://gitlab.com/WuerfelDev/Key8oard/-/blob/master/app/src/main/java/de/wuerfeldev/key8oard/Key8oardIME.java#L30

**Comment by WuerfelDev** [comment]
I also made a small pull request to your code: https://github.com/flide/VI8/pull/22 (havent built it, but it works on Key8oard so should be the same for 8Vim)

Something I haven't thought of is the emoji keyboard. WIth 8Vim the last used keyboard is most likely the emoji keyboard?! 
Like with the emoji keyboard you could add a sharedPref to set the "landscape"-keyboard

**Comment by flide** [comment]
I am still very unsure going into either routes as I don't want to take away the experienced user from the main way he/she types using 8vim. 
But if all else fails and I am not able to codify my vision, I will surely consider these backups (will have to!).

**Comment by Glitchy-Tozier** [comment]
> for 8Vim, in the landscape mode the textfield should be shown on one side of the screen and the keyboard should be shown on another side. This side should be configurable by the user as he/she might prefer left or the right hand.

I really like this!

>I am still very unsure going into either routes as I don't want to take away the experienced user from the main way he/she types using 8vim.

Also, I'm not that big of a fan of switching keyboards. So here is my proposal:

A feature that could make this more comfortable: The Keyboard could always be placed on the side where the android-back-button is and the text-field would always show up on the side of the screen that's usually the top of the screen. Basically, the keyboard stays where it was (it just rotates 90°) and the rest of the screen gets filled with the text-field.

This means:
- User rotates Phone to the right: Keyboard is on the left, text-field is on the right.
- User rotates Phone to the left: Keyboard is on the right, text-field is on the left.

This way, 
1. the user has an easy way to choose which side to have the keyboard on.
2. we get to keep the 8Vim-keyboard active :)

**Comment by MichalLebeda** [comment]
First step would be to at least make landscape mode usable as it is not usable rn

**Comment by atlasveldine** [comment]
This is *desparately* needed. As it stands this app is absolutely unable on larger screens. There's another issue which suggests configurable height for the keyboard which goes hand in hand with this problem. Because the keyboard is so massive, on my Tab S7 it consumes roughly 50% of my screen in portrait and literally all of my screen in landscape. 

![Screenshot_20230410_112944_Via](https://user-images.githubusercontent.com/50584992/230968961-9fa00cc2-4cad-43ec-92d4-421f94e90e81.png)

Samsung Keyboard supports popout mode - in fact, I'm using it to write this message. It allows my keyboard to be transparent and placed above the screens content. This would be incredibly useful for 8vim's style of keyboard - imagine the circle being visible at about 50% opacity, and the remainder of the keyboard at 15% or so.  The screen's content would be almost completely unobstructed. Not to mention, from what I can see with this keyboard, most individuals will only be moving just slightly outside the range of the circle - there's seemingly no need to have literally 4 inches of screen space wasted in every direction outside the circle. Ideally, for my needs at least, the keyboard would only be using up about 2-3 inches of my screen space, and like Samsung's keyboard, allow for popout and a configurable size and transparency. 

![Screenshot_20230410_113258_Via](https://user-images.githubusercontent.com/50584992/230969285-b9db57e4-60ca-49c1-867f-6c298aca6156.png)

Again, as it stands, anyone with a tablet practically can't use this keyboard at all, despite the very same problems with normal keyboards existing on tablets as they do on phones. Sure, the keyboard size is bigger on tablets, but it's equally annoying to use software keyboards on both screen sizes. Further, it appears that the 8vim keyboard scales based on screen width, meaning that users with phone screens with strange aspect ratios where the screen is wider than is typical will suffer even more loss of screen real estate. 

![Screenshot_20230410_113306_Via](https://user-images.githubusercontent.com/50584992/230969373-504b9ac0-4d55-4a41-bbae-05c9747c26f1.png)

This, in my opinion, should be at the top of the development priority list. At the very least, configuring the size and position of the keyboard even without popout, because without this, tablets really can't use this at all. 

Also, remember that adding in additional *options* for accessibility doesn't inherently take away from the way your current users will benefit from the app. When you give users choice how they wish to use your app, you're only broadening your userbase and allowing for people with needs outside the needs of your current user base. In this particular case, i think you'd be surprised at how many users you currently have would appreciate this feature. 

FWIW, I'm disabled and typing on smartphones is, quite literally, very painful for me at times. Luckily today is not a bad day, and I'm on my tablet so the screen is quite large,  but what drew me to your app was the potential accessibility implications. After just briefly demoing the app, I'm uncertain if it'd truly be faster than typing - but, it definitely would be far, far less painful for me. Certainly, I'll use it on my phone in the meantime - my phone which I literally never use because the keyboard is genuinely that painful for me to use in smaller form. 

I hope you decide to implement some kind of functionality which allows for tablets to use your app son, I'm eager to start learning how to type with 8vim.
