### ISSUE TITLE
No letter input on S24 Ultra.

### ISSUE THREAD

**Issue by ypce** [8VIM/8VIM#559]
**Describe the bug**
After installation, setup and restart, no letter input is occuring when swiping normally. Only when drawing a full circle it triggers a vibration and sometimes randomly the letter is triggered. Space works all the time when pressed, same with other buttons.

**To Reproduce**
As in the video.

**Expected behavior**
Letters placed.

**Screenshots**
https://github.com/8VIM/8VIM/assets/19739746/bd51e7b1-069a-494c-8a62-e180764d4503

https://github.com/8VIM/8VIM/assets/19739746/e17c012d-e94f-42ba-a064-8f46bcd69cef

**Smartphone (please complete the following information):**
 - Device: Samsung S24 Ultra SM-S928B/DS
 - OS: One Ul version 6.1, Android version 14
 - Version: 0.17.5

**Comment by ManDay** [comment]
Hello ypce and welcome to 8vim!

It was very constructive of you to upload a video, because from the looks of it, it seems as if your problem is caused by a misunderstanding: To write a letter you have to **start at the center** and **return to the center** after the correct number of turns. To write `D` for example, you start at the center, move to the top, then turn to the left, then to the bottom, and then back to the center.

We are currently working on an introductory video which will hopefully prevent such misunderstandings in the future. Please give a bit of time!

**Comment by ypce** [comment]
Oh yeah you are right!
