### ISSUE TITLE
Create automated test cases 

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#67]
We are currently manually testing the application before releasing. This is not scalable, is boring and feels like time waste.
We need automated tests to verify the application - end to end.

**Comment by cgudea** [comment]
I could look into writing some automated test cases, could you possibly list some of the manual test cases that are performed before a release?

**Comment by flide** [comment]
@cgudea , thanks for extending a helping hand.
As a first line of defense, I am looking for some basic tests like the following in broad terms:

1. All the boards are visible properly on the screen and nothing is clipped.
2. For the button boards, all the buttons are correctly "input-ing" into the textbox.
3. All the gestures are working correctly on the xboard, including all the modifier keys.
4. sidebar on the xboard is working correctly.
5. User is able to switch to the selected keyboard on pressing the emoji button.
6. Various selection features are working correctly with the selection keyboard.

All these basic (although I say basic, this is going to require a lot of effort) tests should be run on multiple devices with variety of screen sizes, resolutions and possibly for all supported android versions.

Currently I do all these tests manually, on one single phone and that happens to be mine. Not really reliable.
But since I use this keyboard as my daily driver if anything is out of place I kind of get to know about it pretty soon. But it's one person on one device testing this. Not very reliable.

**Comment by cgudea** [comment]
I appreciate the indepth response and I agree a single tester on a single device isn't optional 😁. 

To be honest, I'm not entirely sure how to test this. I was trying to write tests for #191 but was unsuccessful on my initial attempt. Since the keyboard is essentially a system ui it's difficult to access the 8VIM UI components when it's active as the IME. Espresso tests can't see the keyboard. I'm going to read through the AOSP keyboard codebase with the hope I can get some inspiration on how to test this. 

I may be able to create a test harness that renders the 8VIM keyboard in an activity/fragment and then test there but something about that feels *wrong*. I'll keep this thread updated as I progress.

**Comment by flide** [comment]
may be looking into florisboard might help. There code base seems to have tests. 
https://github.com/florisboard/florisboard

**Comment by flide** [comment]
Thanks to @MaethorNaur we have a few tests and can build on top of that.
