### ISSUE TITLE
Vibrate indicator option for silence or custom sound to save battery

### ISSUE THREAD

**Issue by Aq32** [8VIM/8VIM#71]
I never used 8pen but discovered 8vim from f-droid. I assume the phone vibrate alert/indicator was something that came with the original app. Would it be possible to change the alert to be silent or a custom selected sound? Another indicator/alert option might be a background colour flash. Whilst unsubstantiated (since I only just started using 8vim) but I think it could save some battery by using a sound or not having any sound at all playing.

**Comment by flide** [comment]
I am really sorry, i could not make sense of your issue... are you reffering to the vibration when each letter is entered? or you talking about some kind of bug?

**Comment by Aq32** [comment]
Yes, when you enter a character or delete or move the cursor forward/backwards it triggers the phone vibration. If you delete a lot of characters or move the cursor direction a lot then it's like a machine gun of vibration which could end up draining the battery.

My suggestion is to give the user an option to change the input character effect so that it doesn't vibrate after every action. Possibly separate the options for _cursor movements and deletes_ from _character input_. I'd like to be able to change the effects of both to silent but some people may prefer to have some effect to show that something has happened.

The effects I'm suggesting could be:
- Silence (no indicator)
- Custom sound clip (user can change)
- Custom colour flash (the 8vim background [currently white] could flash to a different colour the user chooses)
- Vibrate (current default and only option)

**Comment by flide** [comment]
So, I initially put the vibration in so that there is a haptic feedback to the fingers that a character was successfully entered.
Haptic and not sound or flash because I treat this keyboard as a blind typing tool. A lot many of the times I am looking at something else or talking to someone while typing, so both sound and visual cues are useless to me.

But I do understand your point, different people have different preferences. I will definitely think about replacing vibration with sound as a configuration setting but "flash" is ... really not sure... It will be so distracting... I am getting distracted just thinking about it.

**Comment by benhormann** [comment]
"flash" sounds like visual-bell (from the terminal world), not the most popular option out there.

How about highlighting the appropriate letter as the current loop progresses?
As the loop starts draw a highlight around the innermost letter, then as the loop continues around _grow_ the highlight outwards so that it covers the letter that will be produced. You could further emphasise the current letter.

Personally, haptic and/or sound is annoying. Seeing the letter appear is feedback enough.
(I wouldn't oppose making the current letter bold. Something simple and subtle is fine.)

**Comment by m-rey** [comment]
This seems related to the issue I opened, see #92

**Comment by flide** [comment]
I think we will have to have a new issue opened if someone wants a sound instead of haptic feedback or silence as a feedback to the input.
