### ISSUE TITLE
Emoji key switches keyboard altogether

### ISSUE THREAD

**Issue by elig0n** [8VIM/8VIM#80]
No matter what keyboard I select for the emojis, pressing the emoji key changes the current keyboard to it.
Shouldn't it display only the emojis ?

**Comment by flide** [comment]
Well, it is doing what it is expected to do, but I understand your frustration. Try using the sister keyboard for this application to enjoy the intended feature. 
Pictograph keyboard : https://play.google.com/store/apps/details?id=inc.flide.emojiKeyboard
I designed it as such to give users the freedom to choose emoji keyboards of their own liking since I am not able to focus enough on the development of emoji keyboard, but seems to be causing more grief then joy.

Hopefully, you will enjoy the pictograph keyboard in it's current state, it's not bad.
